name: Publish React Storybook Project

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build design-system
        run: npm run build-design-system

      - name: Install build tools
        run: npm install -g yarn

      - name: Package design-system for npm
        run: yarn create-package-json -n @imaginario/storybook

      - name: Update package.json with design-system information
        run: |
          echo "{'main': 'dist/index.js'}" >> package.json
          echo "{'storybook': 'dist/storybook'}" >> package.json

      - name: Publish package to GitHub Packages
        run: npm publish --access public --token ${{ secrets.MY_GITHUB_TOKEN }}
