name: Publish Imaginario Design System

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Design System
        run: npm run build-storybook

      - name: Install build tools
        # Adjust this command based on your actual build tools
        # (e.g., create-package-json for React Storybook)
        run: npm install -g create-package-json

      - name: Package Design System for npm
        # Update the package name if needed
        run: create-package-json -n imaginario

      - name: Update package.json with Design System information
        run: |
          echo "{'main': 'dist/index.js'}" >> package.json
          # Adjust the path based on your actual build output
          echo "{'storybook': 'dist/storybook'}" >> package.json

      - name: Download and install actions/login@v3
        run: |
          curl -fsSL https://raw.githubusercontent.com/actions/login/v3/dist/login.sh | sh -

      - name: Login to npm
        run: ./login.sh
        with:
          registry: https://registry.npmjs.org/
          token: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: npm publish --access public

      - name: Login to GitHub Packages (optional)
        uses: actions/login@v3
        with:
          workflow: ${{ github.workflow }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages (optional)
        run: npm publish --access public --token ${{ secrets.MY_GITHUB_TOKEN }}
