name: Publish Imaginario Design System to npm

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Design System
        run: npm run build-design-system

      - name: Install build tools
        run: npm install -g create-package-json

      - name: Package Design System for npm
        run: create-package-json -n @your-scope/design-system

      - name: Update package.json with Design System information
        run: |
          echo "{'main': 'dist/index.js'}" >> package.json
          echo "{'designSystem': 'dist/design-system'}" >> package.json

      - name: Login to npm
        uses: actions/login@v3
        with:
          registry: https://registry.npmjs.org/
          token: ${{ secrets.NPM_TOKEN }}

      - name: Publish package to GitHub Packages
        run: npm publish --access public --token ${{ secrets.MY_GITHUB_TOKEN }}
