name: Publish Imaginario Design System

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build imaginario
        run: npm run build-storybook

      - name: Install build tools
        # Adjust this command based on your actual build tools
        # (e.g., create-package-json for React Storybook)
        run: npm install -g create-package-json

      - name: imaginario
        # Update the package name if needed
        run: create-package-json -n imaginario

      - name: Update package.json with imaginario information
        run: |
          echo "{'main': 'dist/index.js'}" >> package.json
          # Adjust the path based on your actual build output
          echo "{'storybook': 'dist/storybook'}" >> package.json

      - name: Login to npm
        uses: actions/login@v4
        with:
          registry: https://registry.npmjs.org/
          token: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: npm publish --access public

      - name: Login to GitHub Packages
        uses: actions/login@v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        run: npm publish --access public --token ${{ secrets.MY_GITHUB_TOKEN }}
