name: Publish Imaginario Design System

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook

      # Install create-package-json globally (optional)
      - name: Install build tools
        run: npm install -g create-package-json

      - name: Package Storybook for npm
        run: create-package-json -n @imaginario/design-system

      - name: Update package.json with Storybook information
        run: |
          echo "{'main': 'dist/index.js'}" >> package.json
          echo "{'storybook': 'dist/storybook'}" >> package.json

      - name: Publish package to GitHub Packages
        run: npm publish --access public --token ${{ secrets.MY_GITHUB_TOKEN }}
